# Desc: Styles config for the GUI
# This file is part of ArcticStream Library.

CUSTOM_BAR_HEIGHT = 30
RESIZE_CORNER_SIZE = 10
DEFAULT_PUSH_BUTTON_HEIGHT = 30
DEFAULT_LINE_EDIT_HEIGHT = 30
DEFAULT_LOADING_BAR_HEIGHT = 30
DEBUG_LINE_EDIT_HEIGHT = 25
DEFAULT_STATUS_LEDIT_WIDTH = 500
DEFAULT_STATUS_LEDIT_HEIGH = 25
CONNECTORS_ICON_SIZE = 150