tooltips = {
    "main_window": {
        "ble_button": "Connect to a Bluetooth Low Energy device.",
        "usb_button": "Connect to a device using a serial (UART) connection.",
        "wifi_button": "Connect to a device over WiFi.",
        
        "theme_button": "Toggle between light and dark themes.",
        "accumulator_button": "Toggle data accumulation in console tabs.",
        "top_hint_button": "Keep the window on top of other applications.",
        "autosync_button": "Enable/disable automatic reconnection to the device.",
    },
    "connection_windows": {
        "scan_button": "Scan for available devices.",
        "connect_button": "Connect to the selected device.",
        "disconnect_button": "Disconnect from the currently connected device.",
        "exit_button": "Close the connection window and return to the main interface selection.",
        "device_list": "Double-click on a device to connect.",
    },
    "console_window": {
        "start_button": "Start displaying data in the console.",
        "stop_button": "Pause data display in the console.",
        "clear_button": "Clear the console output.",
        "copy_button": "Copy the console output to the clipboard.",
        "log_button": "Enable/disable logging of console output to a file.",
        "wrap_button": "Toggle text wrapping in the console.",
        "lock_button": "Toggle scroll lock to keep the latest data visible.",
        "send_button": "Send the entered data to the device.",
        "show_timestamp": "Show/hide timestamps and linecounter.",
        "show_metadata": "Show/hide metadata of the console output.",
        "analyze_button": "Analyze and plot the console output.",
    },
    "updater_window": {
        "start_button": "Start the firmware update process.",
        "stop_button": "Stop the ongoing firmware update.",
        "clear_button": "Clear the loaded firmware and information.",
        "reload_button": "Reload the selected firmware file.",
        "folder_button": "Select a firmware (.bin) file for update.",
    },
    "graph_window": {
        "start_button": "Start plotting the data.",
        "stop_button": "Stop plotting the data.",
        "clear_button": "Clear the plotted data.",
        #"save_button": "Save the plot as an image file.",
        #"export_button": "Export the plot data as a CSV file.",
        #"settings_button": "Open the plot settings dialog.",
        #"show_button": "Show/hide the plot window.",
        #"save_settings": "Save the current plot settings.",
        #"load_settings": "Load saved plot settings.",
        "show_var_list_button": "Show/hide the variable list.",
        "show_metadata": "Show/hide metadata of the plot.",
        "device_list": "Select a device to plot data from.",
    },
}
